#!/usr/bin/env bash
# ─── NinjaCommerce stack launcher ───────────────────────────────────────────
# Reads toggles from stack.env (incl. ENV=test|prod), sources the matching
# stack.secrets.$ENV.env, regenerates each app's env file, and boots the stack.
# See stack.env.example / stack.secrets.<env>.env.example.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Generated env files below carry secrets — keep them owner-only.
umask 077

# ── Ports (this machine — see CLAUDE.md) ────────────────────────────────────
API_PORT=3002
STOREFRONT_PORT=3005
ADMIN_PORT=5174

lc() { printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]'; }

# ── Load config ─────────────────────────────────────────────────────────────
[ -f stack.env ] || { echo "❌ Missing stack.env — copy stack.env.example to stack.env"; exit 1; }
set -a; . ./stack.env; set +a

ENV="$(lc "${ENV:-test}")"
case "$ENV" in
  test|prod) ;;
  *) echo "❌ ENV must be 'test' or 'prod' (got '$ENV')"; exit 1 ;;
esac

SECRETS="stack.secrets.${ENV}.env"
[ -f "$SECRETS" ] || { echo "❌ Missing $SECRETS — copy ${SECRETS}.example and fill it in"; exit 1; }
set -a; . "./$SECRETS"; set +a

DB_EMU="$(lc "${DATABASE_EMULATOR:-true}")"
BE_LOCAL="$(lc "${BACKEND_URL:-true}")"
LAN_EXPOSE="$(lc "${LAN_EXPOSE:-false}")"

# LAN exposure is OPT-IN. When off (default), servers bind loopback only and no
# LAN origins are added to CORS. When on, we detect this machine's LAN IP and
# bind all interfaces so other devices on the network can reach the dev servers.
if [ "$LAN_EXPOSE" = "true" ]; then
  LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
  BIND_HOST=0.0.0.0
else
  LAN_IP=""
  BIND_HOST=127.0.0.1
fi

echo "🔧 ENV=$ENV  DATABASE_EMULATOR=$DB_EMU  BACKEND_URL=$BE_LOCAL  LAN_EXPOSE=$LAN_EXPOSE"
if [ "$ENV" = "prod" ]; then
  echo "   ⚠️  PRODUCTION environment — real Firebase users + real Supabase data."
  echo "       (Local checkout still uses the Stripe TEST key — no live charges from your laptop.)"
fi

# ── Resolve values ──────────────────────────────────────────────────────────
MISSING=0
need() {  # NAME VALUE
  if [ -z "${2:-}" ] || printf '%s' "$2" | grep -qE 'REPLACE_ME'; then
    echo "   ❌ $1 is unset/placeholder in $SECRETS"; MISSING=1
  fi
}

need FIREBASE_API_KEY "${FIREBASE_API_KEY:-}"
need FIREBASE_AUTH_DOMAIN "${FIREBASE_AUTH_DOMAIN:-}"
need FIREBASE_PROJECT_ID "${FIREBASE_PROJECT_ID:-}"

if [ "$DB_EMU" = "false" ]; then
  need DATABASE_URL "${DATABASE_URL:-}"
  API_DATABASE_URL="${DATABASE_URL:-}"
else
  API_DATABASE_URL="${LOCAL_DATABASE_URL:-postgresql://ecommerce:ecommerce@localhost:5432/ecommerce}"
fi

if [ "$BE_LOCAL" = "true" ]; then
  FRONTEND_API_URL="http://localhost:${API_PORT}"
else
  need DEPLOYED_API_URL "${DEPLOYED_API_URL:-}"
  FRONTEND_API_URL="${DEPLOYED_API_URL:-}"
  [ "$DB_EMU" = "true" ] && echo "   ⚠️  BACKEND_URL=false → frontends use the deployed API; DATABASE_EMULATOR is ignored (no local API runs)."
fi

# The local API ALWAYS uses the Stripe TEST key (STRIPE_SECRET_KEY in the secrets
# files is the test key). The live key lives only in STRIPE_SECRET_KEY_LIVE (prod
# file, deploy-only) and is NEVER written to a local .env — so a laptop can't fire
# a real charge, even in ENV=prod.
LOCAL_STRIPE_KEY="${STRIPE_SECRET_KEY:-sk_test_placeholder}"
LOCAL_STRIPE_WHSEC="${STRIPE_WEBHOOK_SECRET:-whsec_placeholder}"

if [ "$MISSING" = "1" ]; then
  echo "❌ Fill the values above in $SECRETS and re-run."; exit 1
fi

# ── Regenerate per-app env files ────────────────────────────────────────────
echo "📝 writing env files"
cat > ecommerce-api/.env <<EOF
# GENERATED by start-stack.sh (ENV=$ENV) — edit stack.env / $SECRETS, not this file.
DATABASE_URL=${API_DATABASE_URL}
PORT=${API_PORT}
HOST=${BIND_HOST}
STRIPE_SECRET_KEY=${LOCAL_STRIPE_KEY}
STRIPE_WEBHOOK_SECRET=${LOCAL_STRIPE_WHSEC}
FRONTEND_URL=http://localhost:${STOREFRONT_PORT}
CORS_ORIGINS=http://localhost:${STOREFRONT_PORT},http://localhost:${ADMIN_PORT}$([ -n "$LAN_IP" ] && echo ",http://${LAN_IP}:${STOREFRONT_PORT},http://${LAN_IP}:${ADMIN_PORT}")
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
# Firebase auth is always live — FIREBASE_AUTH_EMULATOR_HOST intentionally unset.
EOF

# NOTE: target file is .env.development.local — the HIGHEST-priority env file in
# BOTH Next.js and Vite (dev mode). Vite ranks a committed .env.development ABOVE
# .env.local, so writing .env.local would be silently ignored by the admin.
rm -f ecommerce-storefront/.env.local ecommerce-admin/.env.local  # clear stale lower-priority files
cat > ecommerce-storefront/.env.development.local <<EOF
# GENERATED by start-stack.sh (ENV=$ENV) — edit stack.env / $SECRETS, not this file.
NEXT_PUBLIC_API_URL=${FRONTEND_API_URL}
NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
NEXT_PUBLIC_USE_EMULATORS=false
NEXT_PUBLIC_ADDRESSCOMPLETE_KEY=${NEXT_PUBLIC_ADDRESSCOMPLETE_KEY:-}
EOF

cat > ecommerce-admin/.env.development.local <<EOF
# GENERATED by start-stack.sh (ENV=$ENV) — edit stack.env / $SECRETS, not this file.
VITE_API_URL=${FRONTEND_API_URL}
VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-${FIREBASE_PROJECT_ID}.firebasestorage.app}
VITE_USE_EMULATORS=false
EOF

# ── Stop anything we started before ─────────────────────────────────────────
mkdir -p .stack/logs .stack/pids
"$ROOT/stop-stack.sh" --quiet || true

start_svc() {  # NAME  WORKDIR  CMD...
  local name="$1" wd="$2"; shift 2
  echo "   ▶️  $name"
  ( cd "$wd" && nohup "$@" > "$ROOT/.stack/logs/$name.log" 2>&1 & echo $! > "$ROOT/.stack/pids/$name.pid" )
}

# ── Boot ────────────────────────────────────────────────────────────────────
echo "🚀 booting…"
if [ "$BE_LOCAL" = "true" ]; then
  if [ "$DB_EMU" = "true" ]; then
    echo "   🐘 docker postgres"
    ( cd ecommerce-api && docker compose up -d db )
    echo -n "   ⏳ waiting for postgres"
    for _ in $(seq 1 30); do
      if ( cd ecommerce-api && docker compose exec -T db pg_isready -U ecommerce >/dev/null 2>&1 ); then echo " ✓"; break; fi
      printf '.'; sleep 1
    done
    ( cd ecommerce-api && npx prisma migrate deploy ) || echo "   ⚠️  prisma migrate deploy failed — check ecommerce-api migrations"
  fi
  start_svc api ecommerce-api env "PORT=${API_PORT}" npm run start:dev
fi
start_svc storefront ecommerce-storefront env "PORT=${STOREFRONT_PORT}" npm run dev -- --hostname "${BIND_HOST}"
start_svc admin      ecommerce-admin      npm run dev -- --host "${BIND_HOST}"

# ── Summary ─────────────────────────────────────────────────────────────────
cat <<EOF

✅ stack started  (ENV=$ENV)
   storefront → http://localhost:${STOREFRONT_PORT}$([ -n "$LAN_IP" ] && echo "   (LAN: http://${LAN_IP}:${STOREFRONT_PORT})")   (Firebase: ${FIREBASE_PROJECT_ID})
   admin      → http://localhost:${ADMIN_PORT}$([ -n "$LAN_IP" ] && echo "   (LAN: http://${LAN_IP}:${ADMIN_PORT})")
$([ "$BE_LOCAL" = "true" ] && echo "   api        → http://localhost:${API_PORT}   (db: $([ "$DB_EMU" = "true" ] && echo 'local docker' || echo "supabase [$ENV]"))" || echo "   api        → ${FRONTEND_API_URL}   (deployed)")

   logs:  tail -f .stack/logs/<api|storefront|admin>.log
   stop:  ./stop-stack.sh
EOF
